name: Sync zlib-ng from CachyOS

on:
  schedule:
    - cron: '0 0 * * *'  # Runs once a day at midnight UTC
  push:
    branches:
      - main  # Trigger on changes to the main branch

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout your repository
      uses: actions/checkout@v2
      
    - name: Clone CachyOS repository
      run: |
        git clone --depth 1 https://github.com/CachyOS/CachyOS-PKGBUILDS.git
        cp -r CachyOS-PKGBUILDS/zlib-ng/* .

    - name: Commit and push changes
      run: |
        git config --global user.name "Your GitHub Username"
        git config --global user.email "your-email@example.com"
        git add .
        git commit -m "Updated zlib-ng from CachyOS-PKGBUILDS" || echo "No changes to commit"
        git push
